### ISSUE TITLE
Tiles width too large

### ISSUE THREAD

**Issue by JBSoft** [flatsiedatsie/domoticz-aurora-theme#4]
See below some issues with tiles width, and the parameters I have if that can help to solve the issue.

Thanks.

jeanclic.

![2018-01-10 17_27_37-domoticz_dashboard](https://user-images.githubusercontent.com/20253547/34783462-f0c6ead4-f62b-11e7-9bd3-6295a460cd8d.png)
![2018-01-10 17_27_37-domoticz_themeoptions](https://user-images.githubusercontent.com/20253547/34783463-f0e9b26c-f62b-11e7-8f0b-e9aa3a783cbc.png)

**Comment by JBSoft** [comment]
Other issues in the same spirit :
![image](https://user-images.githubusercontent.com/20253547/34783778-beaffc42-f62c-11e7-9998-9fbe979272a2.png)
![image](https://user-images.githubusercontent.com/20253547/34783830-e2311c50-f62c-11e7-99d3-a083c365a865.png)

**Comment by JBSoft** [comment]
another one :
![image](https://user-images.githubusercontent.com/20253547/34784516-c21a0786-f62e-11e7-8f84-1a7b470d1e40.png)
-> good for temperatures, but not for switches.

**Comment by flatsiedatsie** [comment]
Thanks! These should be fixed.

**Comment by JBSoft** [comment]
Sorry, but not completely corrected for me: first issue of this list is corrected, but only if I do not redim my window from a small size (3 columns) to a full size (5 columns) or reverse.
see on firefox for an example:
![image](https://user-images.githubusercontent.com/20253547/35030277-ba00fdb8-fb5e-11e7-9866-951799e93f2a.png)

Other issues are definitely still there for me.

**Comment by flatsiedatsie** [comment]
Do you still have the issues on the latest version?

**Comment by JBSoft** [comment]
Hello,

My settings are still like I have shown in the issue description.
I still have the tiles issues:
![image](https://user-images.githubusercontent.com/20253547/35480005-185ec7e2-0405-11e8-9309-74e8b8cc9108.png)
![image](https://user-images.githubusercontent.com/20253547/35480011-3a0dfd2c-0405-11e8-87f5-432f9b98e898.png)
![image](https://user-images.githubusercontent.com/20253547/35480014-5d1e1914-0405-11e8-86d2-867b1464dee9.png)
As you can see, for the last column, it is good for the temperatures (same for weather). (even if I try to enlarge a lot bigger).
![image](https://user-images.githubusercontent.com/20253547/35480028-d009b60e-0405-11e8-9319-2d39fdea719e.png)
But it is still not good for the switches and the measures...
That was in NORMAL view.

Below is in COMPACT view:
![image](https://user-images.githubusercontent.com/20253547/35480054-a5f418c2-0406-11e8-92ed-96f1cf09d586.png)
Thanks for the occasion to test it ! (I don't use it at all).

Anyway, the theme is quite stable, in usage on my wall tablet for some weeks now, thanks a lot for the already massive work you have done !

**Comment by flatsiedatsie** [comment]
Found the bug! thanks!

**Comment by JBSoft** [comment]
Nice job ! thanks. Ok for the feature, I wasn't sure ;).

For the overlapping issue, you need to be in compact mode, and having a multiple level switch with 5 levels in my case. that forces the tile to enlarge too much. Don't know if it is clear for you ?

**Comment by JBSoft** [comment]
sorry wrong button : not close !

**Comment by flatsiedatsie** [comment]
Ok, but there's not much I can do about that. Don't use the compact option if you have so many button in an item.
